# Generated by Django 5.0 on 2023-12-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snf', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adc_water', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
